<?php
/**
 * Created by PhpStorm.
 * User: manuelmeister
 * Date: 12.05.15
 * Time: 15:45
 */

namespace Meister\MVC\Controller;


class DefaultController extends Controller {

    public function index($name = __CLASS__)
    {
        parent::index($name); // TODO: Change the autogenerated stub
    }

}